//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public int FisrtUserId { get; set; }
        public int SecondUserId { get; set; }
        public string ConnectionString { get; set; }
        public string Pass { get; set; }
    
        public virtual User Users { get; set; }
        public virtual User Users1 { get; set; }
    }
}
